gOtherText_NewName:: @ 81C574F
    .string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
    .string "KAIZO$"

gNameChoice_Red:: @ 81C575E
    .string "RED$"

gNameChoice_Leaf:: @ 81C5762
    .string "LEAF$"

gNameChoice_Fire:: @ 81C5767
    .string "FIRE$"

gNameChoice_Gary:: @ 81C576C
    .string "CHAT$"

gNameChoice_Kaz:: @ 81C5771
    .string "KAZ$"

gNameChoice_Toru:: @ 81C5775
    .string "TORU$"

gNameChoice_Ash:: @ 81C577A
    .string "ASH$"

gNameChoice_Kene:: @ 81C577E
    .string "KENE$"

gNameChoice_Geki:: @ 81C5783
    .string "GEKI$"

gNameChoice_Jak:: @ 81C5788
    .string "JAK$"

gNameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gNameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gNameChoice_Karl:: @ 81C579D
    .string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gNameChoice_Max:: @ 81C57B4
    .string "MAX$"

gNameChoice_Jon:: @ 81C57B8
    .string "JON$"

gNameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gNameChoice_June:: @ 81C57FA
    .string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
    .string "REY$"

gNameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gNameChoice_Mina:: @ 81C5814
    .string "MINA$"

gNameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gNameChoice_Sai:: @ 81C581F
    .string "SAI$"

gNameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "Included here are the various IronMon   \n"
    .string "resources at your disposal    $"

gNewGame_HelpDocs2:: @ 81C5875
    .string "IronMon Community Discord\n"
    .string "https://discord.gg/jFPYsZAhjX   \n"
    .string "Be Nice! $"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "Find the Rando here, as well as\n"
    .string "settings, rules, and more info$"

gNewGame_HelpDocs4:: @ 81C58F9
    .string "You can post accomplishments, \n"
    .string "& IronMon streams.$"

gNewGame_HelpDocs5:: @ 81C592B
    .string "IronMon Rules Pastebins:     \n"
    .string "     $"

gNewGame_HelpDocs6:: @ 81C594F
    .string "IronMon rules are preferences \n"
    .string "Kaizo's are strict$"

gNewGame_HelpDocs7:: @ 81C5981
    .string "Kaizo: pastebin.com/sqgFDYME\n"
    .string "Classic & Ultimate IronMon:  \n"
    .string "pastebin.com/L48bttfz   $"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gNewGameAdventureIntro1::
    .string "In the world which you are about to\n"
    .string "enter, you will encounter grand \n"
    .string "challenges around every corner.\n"
    .string "\n"
    .string "Take great care of your POKéMON \n"
    .string "and train hard. Be sure to use your \n"
    .string "items wisely, and do not take   \n"
    .string "trainer battles lightly.$"

gNewGameAdventureIntro2::
    .string "Use the available resources to find  \n"
    .string "hidden items, and skip any battle that\n"
    .string "may be too dangerous. \n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gNewGameAdventureIntro3::
    .string "During this challenge, we hope \n"
    .string "that through the toughest times, you \n"
    .string "will persevere and enjoy this game.   \n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of IronMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gOakText_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pYour very own POKéMON legend is\n"
    .string "about to unfold!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
